/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoloIndexRouteImport } from './routes/solo/index'
import { Route as RankedIndexRouteImport } from './routes/ranked/index'
import { Route as SoloDifficultyRouteImport } from './routes/solo/$difficulty'
import { Route as RankedMatchMatchIdRouteImport } from './routes/ranked/match.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloIndexRoute = SoloIndexRouteImport.update({
  id: '/solo/',
  path: '/solo/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankedIndexRoute = RankedIndexRouteImport.update({
  id: '/ranked/',
  path: '/ranked/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloDifficultyRoute = SoloDifficultyRouteImport.update({
  id: '/solo/$difficulty',
  path: '/solo/$difficulty',
  getParentRoute: () => rootRouteImport,
} as any)
const RankedMatchMatchIdRoute = RankedMatchMatchIdRouteImport.update({
  id: '/ranked/match/$matchId',
  path: '/ranked/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solo/$difficulty': typeof SoloDifficultyRoute
  '/ranked/': typeof RankedIndexRoute
  '/solo/': typeof SoloIndexRoute
  '/ranked/match/$matchId': typeof RankedMatchMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solo/$difficulty': typeof SoloDifficultyRoute
  '/ranked': typeof RankedIndexRoute
  '/solo': typeof SoloIndexRoute
  '/ranked/match/$matchId': typeof RankedMatchMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solo/$difficulty': typeof SoloDifficultyRoute
  '/ranked/': typeof RankedIndexRoute
  '/solo/': typeof SoloIndexRoute
  '/ranked/match/$matchId': typeof RankedMatchMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/solo/$difficulty'
    | '/ranked/'
    | '/solo/'
    | '/ranked/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/solo/$difficulty' | '/ranked' | '/solo' | '/ranked/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/solo/$difficulty'
    | '/ranked/'
    | '/solo/'
    | '/ranked/match/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SoloDifficultyRoute: typeof SoloDifficultyRoute
  RankedIndexRoute: typeof RankedIndexRoute
  SoloIndexRoute: typeof SoloIndexRoute
  RankedMatchMatchIdRoute: typeof RankedMatchMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo/': {
      id: '/solo/'
      path: '/solo'
      fullPath: '/solo/'
      preLoaderRoute: typeof SoloIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranked/': {
      id: '/ranked/'
      path: '/ranked'
      fullPath: '/ranked/'
      preLoaderRoute: typeof RankedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo/$difficulty': {
      id: '/solo/$difficulty'
      path: '/solo/$difficulty'
      fullPath: '/solo/$difficulty'
      preLoaderRoute: typeof SoloDifficultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranked/match/$matchId': {
      id: '/ranked/match/$matchId'
      path: '/ranked/match/$matchId'
      fullPath: '/ranked/match/$matchId'
      preLoaderRoute: typeof RankedMatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SoloDifficultyRoute: SoloDifficultyRoute,
  RankedIndexRoute: RankedIndexRoute,
  SoloIndexRoute: SoloIndexRoute,
  RankedMatchMatchIdRoute: RankedMatchMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
