/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SoloIndexImport } from './routes/solo/index'
import { Route as RankedIndexImport } from './routes/ranked/index'
import { Route as SoloDifficultyImport } from './routes/solo/$difficulty'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SoloIndexRoute = SoloIndexImport.update({
  id: '/solo/',
  path: '/solo/',
  getParentRoute: () => rootRoute,
} as any)

const RankedIndexRoute = RankedIndexImport.update({
  id: '/ranked/',
  path: '/ranked/',
  getParentRoute: () => rootRoute,
} as any)

const SoloDifficultyRoute = SoloDifficultyImport.update({
  id: '/solo/$difficulty',
  path: '/solo/$difficulty',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ranked/': {
      id: '/ranked/'
      path: '/ranked'
      fullPath: '/ranked'
      preLoaderRoute: typeof RankedIndexImport
      parentRoute: typeof rootRoute
    }
    '/solo/': {
      id: '/solo/'
      path: '/solo'
      fullPath: '/solo'
      preLoaderRoute: typeof SoloIndexImport
      parentRoute: typeof rootRoute
    }
    '/solo/$difficulty': {
      id: '/solo/$difficulty'
      path: '/solo/$difficulty'
      fullPath: '/solo/$difficulty'
      preLoaderRoute: typeof SoloDifficultyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ranked': typeof RankedIndexRoute
  '/solo': typeof SoloIndexRoute
  '/solo/$difficulty': typeof SoloDifficultyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ranked': typeof RankedIndexRoute
  '/solo': typeof SoloIndexRoute
  '/solo/$difficulty': typeof SoloDifficultyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ranked/': typeof RankedIndexRoute
  '/solo/': typeof SoloIndexRoute
  '/solo/$difficulty': typeof SoloDifficultyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ranked' | '/solo' | '/solo/$difficulty'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ranked' | '/solo' | '/solo/$difficulty'
  id: '__root__' | '/' | '/ranked/' | '/solo/' | '/solo/$difficulty'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RankedIndexRoute: typeof RankedIndexRoute
  SoloIndexRoute: typeof SoloIndexRoute
  SoloDifficultyRoute: typeof SoloDifficultyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RankedIndexRoute: RankedIndexRoute,
  SoloIndexRoute: SoloIndexRoute,
  SoloDifficultyRoute: SoloDifficultyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
